# Generated by Django 3.2 on 2021-04-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place_of_birth', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('biography', models.TextField()),
                ('education', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='artists/')),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind_of_work', models.TextField()),
                ('date', models.DateField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('volume', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='artworks/')),
                ('artist', models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='rest.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.TextField()),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='exhibitions/')),
                ('artworks', models.ManyToManyField(to='rest.Artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='owners/')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('square', models.FloatField()),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='exhibitionHalls/')),
                ('exhibitions', models.ManyToManyField(to='rest.Exhibition')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.owner')),
            ],
        ),
    ]
