# Generated by Django 3.2 on 2021-04-16 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExhibitionsWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='ExhibitionsWebApp.artist'),
        ),
    ]
