# Generated by Django 3.2 on 2021-04-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExhibitionsWebApp', '0003_exhibitionhall_exhibitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionhall',
            name='exhibitions',
            field=models.ManyToManyField(to='ExhibitionsWebApp.Exhibition'),
        ),
    ]
